Feature/create product
ihsyamdev/order-management-dev pull request #7
Opened 2023-02-28 02:30 UTC by shoki-pri

勉強会-Product機能の実装

2023-02-28 05:29 UTC, ihsyamdev commented on README.md
> -```c
この辺の不要な更新は外しといてほしい
git addする時にファイルを直接指定するなりで、Upload対象から外すとか

2023-02-28 05:30 UTC, ihsyamdev commented on package.json
> +    "@types/uuid": "^9.0.1",
不要なパッケージが追加されてるので、npm uninstall @types/uuidとかで削除しておいてほしい
必要ならどこで使ってるか教えてほしい

2023-02-28 05:31 UTC, ihsyamdev commented on prisma/schema.prisma
> +}
すべてアッパーキャメルケースで統一してほしい
少なくともスネークケースとの同居はなしで

2023-02-28 05:33 UTC, ihsyamdev commented on src/application/product/product.controller.ts
> +  @Get(':ProductId')
基本的に、型 = Upperキャメルケース、オブジェクトや変数 = Lowerキャメルケースで統一してほしい
ここは変数なのでLowerキャメルケースがいい

2023-02-28 05:34 UTC, ihsyamdev commented on src/application/product/product.controller.ts
> +  @Post()
ProductModelの修正と一緒に対応してほしい
JSONで受け取る場合、内部はLowerキャメルケースが一般的なので、修正してほしい

2023-02-28 05:35 UTC, ihsyamdev commented on src/domain/entities/product.entity.ts
> +  }
TypeScriptにおいてはスネークケースはどうしても必要な場合以外は使わない
Upper/ Lowerキャメルケースで統一する

2023-02-28 05:35 UTC, ihsyamdev commented on src/infrastructure/prisma/product.prisma.repository.ts
> +    console.log('product-prisma-repository-all')
不要なconsole.log()は削除する

2023-02-28 05:36 UTC, ihsyamdev commented on src/infrastructure/prisma/product.prisma.repository.ts
> +    return new Product(
モデルの修正に合わせて対応おなしゃす

2023-02-28 05:36 UTC, ihsyamdev commented on src/infrastructure/prisma/product.prisma.repository.ts
> +    console.log('product-prisma-repository-one')
不要なconsole.log()は削除する

2023-02-28 05:37 UTC, ihsyamdev requested changes
一通りレビューした
修正してほしい箇所がいくつかあるので対応お願いします

2023-03-02 15:49 UTC, ihsyamdev approved these changes
LTGM

2023-03-02 15:54 UTC, merged

2023-03-02 15:55 UTC, shoki-pri commented
確認ありがとうございました